# Generated by Django 5.1.3 on 2025-06-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=25)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
